FROM php:8.3-fpm-alpine 

# installation des paquets nécessaires
RUN apk add --no-cache \
    git \
    unzip \
    icu-dev \
    oniguruma-dev \
    libzip-dev \
    zlib-dev \
    autoconf \
    g++ \
    make \
    libtool \
    pkgconfig \
    libxml2-dev \
    openssl-dev \
    && docker-php-ext-install intl pdo_mysql opcache zip

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

# copie le code source dans l'image
COPY . .

RUN composer install --no-interaction --prefer-dist --optimize-autoloader || true

# permissions (en dev)
RUN chown -R www-data:www-data var

EXPOSE 9000


